apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: dimarino/fastapi:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: REDIS_HOST
          value: "fastapi.tweff2.ng.0001.use1.cache.amazonaws.com"
        - name: REDIS_PORT
          value: "6379"
        - name: UVICORN_HOST
          value: "0.0.0.0"
        - name: UVICORN_RELOAD
          value: "False"
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
  replicas: 3
