version: '3.9'

services:

  redis:
    image: redis:latest
    command: --appendonly yes
    restart: always
    volumes:
      - ~/git/fastapi/docker-compose/data/redis:/data
    ports:
      - 6379:6379
